spring:
  application:
    name: hub-service
  profiles:
    active: local
    include:
      - datasource
      - service
      - redis

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 19092