global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: "prometheus"

# 각 마이크로서비스별로 추가
#  - job_name: 'user-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 1s
#    static_configs:
#      - targets: ['grafana:8081']
#        labels:
#          service: 'user'

  - job_name: 'company-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          service: 'company'

