spring:
  application:
    name: api-gateway

  config:
    import:
      optional:configserver:http://localhost:8888
  main:
    web-application-type: reactive
  cloud:
    config:
      fail-fast: false

    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

            - id: user-swagger
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/user-service, /v3/api-docs

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**,/api/v1/product-categories/**,/api/v1/stocks/**,/api/v1/products/**

            - id: company-swagger
              uri: lb://company-service
              predicates:
                - Path=/v3/api-docs/company-service
              filters:
                - RewritePath=/v3/api-docs/company-service, /v3/api-docs

            - id: notification-service
              uri:
                http://localhost:8089
              predicates:
                - Path=/api/v1/ai-delivery/**

springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: company-service
        url: /v3/api-docs/company-service
      - name: user-service
        url: /v3/api-docs/user-service

server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
