jwt:
  secret: "sdfu2893rwefsd8f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832f"
  expiration: 3600000
spring:
  profiles:
    include: actuator
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- swagger 라우팅 설정 ---
            - id: order-service-docs
              uri: lb://order-service
              predicates:
                - Path=/v3/api-docs/order-service
              filters:
                - RewritePath=/v3/api-docs/order-service(?<segment>.*), /v3/api-docs${segment}
            - id: user-service-docs
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/user-service(?<segment>.*), /v3/api-docs${segment}

            - id: company-service-docs
              uri: lb://company-service
              predicates:
                - Path=/v3/api-docs/company-service
              filters:
                - RewritePath=/v3/api-docs/company-service(?<segment>.*), /v3/api-docs${segment}

            - id: hub-service-docs
              uri: lb://hub-service
              predicates:
                - Path=/v3/api-docs/hub-service
              filters:
                - RewritePath=/v3/api-docs/hub-service(?<segment>.*), /v3/api-docs${segment}
            # --- 서비스 라우팅 설정 ---
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**,/api/v1/product-categories/**,/api/v1/stocks/**,/api/v1/products/**
            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/api/v1/hubs/**,/api/v1/hub-routes/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**,/api/v1/deliveries/**
            - id: notification-service
              uri: http://localhost:8089
              predicates:
                - Path=/api/v1/ai-delivery/**

server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: company-service
        url: /v3/api-docs/company-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: hub-service
        url: /v3/api-docs/hub-service
      - name: order-service
        url: /v3/api-docs/order-service
---

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka