spring:
  application:
    name: api-gateway
  profiles:
    include:
      - eureka

  config:
    import: configserver:http://localhost:8888

  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081 #TODO : 8081???? ???, lb://USER-SERVICE? ????? ??
              predicates:
                - Path=/api/v1/users/**

            - id: notification-service
              uri:
                http://localhost:8089
              predicates:
                - Path=/api/v1/ai-delivery/**

#jwt:
#  secret: "sdfu2893rwefsd8f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832f"
#  expiration: 3600000
server:
  port: 8000
