server:
  port: 8082

spring:
  application:
    name: company-service

  profiles:
    include:
      - redis
      - datasource
      - service
      - actuator
      - eureka
      - zipkin
      - config
      - swagger