spring:
  config:
    activate:
      on-profile: test, local

user-service:
  url: http://localhost:8081
company-service:
  url: http://localhost:8082

---

spring:
  config:
    activate:
      on-profile: dev

user-service:
  url: http://dev-user-service:8081
company-service:
  url: http://localhost:8082
---

spring:
  config:
    activate:
      on-profile: prod

user-service:
  url: http://prod-user-service:8081
company-service:
  url: http://localhost:8082

---

spring:
  config:
    activate:
      on-profile: docker

user-service:
  url: http://user-service:8081
company-service:
  url: http://company-service:8082