server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import:
      optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false

  profiles:
    include:
      - datasource
      - eureka
      - actuator
      - zipkin
      - swagger
    active: test

jwt:
  secret: "asda2sdaidasdsa5d67sa56d75267d5675s67d5a67w567d56wa"          # JWT 서명에 사용할 비밀키
  expiration: 3600000