server:
  port: 8081

spring:
  application:
    name: user-service

  profiles:
    include:
      - datasource
      - eureka
      - actuator
      - zipkin
      - swagger
    active: test
---
server:
  port: 8081

spring:
  application:
    name: user-service

  profiles:
    include:
      - datasource
      - eureka
      - actuator
      - zipkin
      - swagger
    active: docker