server:
  port: 8081

spring:
  profiles:
    include:
      - datasource
    active: test

# TODO : configure-service? ??
jwt:
  secret: "sdfu2893rwefsd8f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832fsd9f7sdf9832f"
  expiration: 3600000