spring:
  config:
    activate:
      on-profile: test, local

user-service:
  url: http://localhost:8081
order-service:
  url: http://localhost:8080
company-service:
  url: http://localhost:8082
hub-service:
  url: http://localhost:8083
delivery-service:
  url: http://localhost:8080
---

spring:
  config:
    activate:
      on-profile: dev

user-service:
  url: http://dev-user-service:8081
order-service:
  url: http://dev-order-service:8080
company-service:
  url: http://dev-company-service:8082
hub-service:
  url: http://dev-hub-service:8083
delivery-service:
  url: http://dev-delivery-service:8080
---

spring:
  config:
    activate:
      on-profile: prod

user-service:
  url: http://prod-user-service:8081
order-service:
  url: http://prod-order-service:8080
company-service:
  url: http://prod-company-service:8082
hub-service:
  url: http://prod-hub-service:8083
delivery-service:
  url: http://prod-delivery-service:8080