spring:
  profiles:
    include:
      - service
      - datasource
      - actuator
      - config
      - eureka
      - swagger
      - zipkin
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.shoonglogitics.orderservice: DEBUG
