spring:
  application:
    name: order-service
  config:
    import:
      optional:configserver:http://localhost:8888
    activate:
      on-profile: test, local, dev
  cloud:
    config:
      fail-fast: false
---
spring:
  application:
    name: order-service
  config:
    import:
      optional:configserver:http://configure-service:8888
    activate:
      on-profile: docker
  cloud:
    config:
      fail-fast: false